apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-botpress-pv
spec:
  capacity:
    storage: 10Gi
    #volumeMode: FileSystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-botpress
  #mountOptions:
  #- hard
  #- nfsvers=4.0
  nfs:
    path: /your-nfs-botpress-data-path
    server: 127.0.0.1
