apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-botpress-pvc
  namespace: dit
spec:
  storageClassName: nfs-botpress
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
