apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-postgresql-pvc
  namespace: default
spec:
  storageClassName: nfs-postgresql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
