apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-postgresql-pv
spec:
  capacity:
    storage: 10Gi
    #volumeMode: FileSystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-postgresql
  #mountOptions:
  #- hard
  #- nfsvers=4.0
  nfs:
    path: /var/nfs/botpress/postgresql/data
    server: 148.231.10.217
