apiVersion: apps/v1
kind: Deployment
metadata:
  name: botpress-deployment-prueba
  namespace: dit
  labels:
    app: botpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botpress
  template:
    metadata:
      labels:
        app: botpress
    spec:
      initContainers:
      - name: wait-for-postgresdb-connection
        image: postgres:alpine3.17
        ports:
          - containerPort: 5432
        command:  ["sh", "-c", 
        "until pg_isready -h postgres-service.dit -p 5432; 
          do echo waiting for database; sleep 2; done;"]                      
      containers:
      - name: botpress
        image: botpress/server:v12_29_1
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /botpress/data
            name: pv-storage
        env:
        - name: BPFS_STORAGE
          value: "database"        
        - name: AUTO_MIGRATE
          value: "true"                  
        - name: CI_EMAIL
          value: "test@gmail.com"                  
        - name: CI_PASSWORD
          value: "!Hola1234"                  
        - name: DATABASE_URL
          value: "postgresql://admin:mysecretpassword@postgres-service.dit:5432/botpress"       
        - name: EXTERNAL_URL
          value: "https://demo.localdev.me/botpress"                          
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: nfs-botpress-pvc
