apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-prueba
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:      
      containers:
      - name: postgres
        image: postgres:alpine3.17
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pv-storage
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"             
        - name: POSTGRES_USER
          value: "admin"             
        - name: POSTGRES_DB
          value: "botpress"    
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: nfs-postgresql-pvc
